### PR TITLE
Version 1.3.4 : add timestamp and increase log readability

### PR DESCRIPTION
**Pull request by lapineige**
https://github.com/mcrudelis/archivist/pull/18

## PR Status

- [x] Code finished and ready to be reviewed/tested
- [x] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by mcrudelis** [comment]
Change my account since github enforce 2FA without letting any other options...
I don't have permission on this repo anymore.

**Comment by lapineige** [comment]
Oh ok.
ping @YunoHost-Apps then

**Comment by lapineige** [comment]
!testme

**Comment by mcrudelis** [comment]
> Changed my account since github enforce 2FA without letting any other options... I don't have permission on this repo anymore.

Happening again with this new account.
I'll leave github for good that time.
Worth knowing since that means that archivist (and my other apps) won't be on github anymore. Maybe gitlab...

**Comment by lapineige** [comment]
Oh so this would mean changing the repo URL in that app then.
For your information 2FA is now mandatory in any github account.

Then it would be nice if I could have write access to this repo to manage it if needed :) (I'm kind of willing to help maintaining it :)

**Comment by lapineige** [comment]
!testme

**Pull request merged**
